class ChecklistData {
  // ==========================================
  // CHECK IN TRACTOR (61 ÍTEMS TOTAL)
  // ==========================================
  static const Map<String, List<String>> itemsTractor = {
    "EXTERIOR": [
      "1. GUARDABARROS",
      "2. PUERTAS",
      "3. CARENADOS",
      "4. PARABRISA",
      "5. VENTANAS PUERTAS",
      "6. VISERA",
      "7. ESPEJOS RETROVISORES",
      "8. ESCOBILLAS LIMPIAPARABRISAS",
      "9. CAJA BATERIAS",
      "10. BATERIAS(INSPECCION VISUAL)",
      "11. PARAGOLPE DELANTERO",
      "12. PARAGOLPE TRASERO",
      "13. REJILLAS FRONTALES",
      "14. TANQUES DE COMBUSTIBLES/TAPAS",
      "15. TANQUE ADBLUE/TAPA",
      "16. PATENTE DELANTERA",
      "17. PATENTE TRASERA",
      "18. OPTICAS DELANTERAS",
      "19. OPTICAS TRASERAS"
    ],
    "ACCESORIOS": [
      "20. BALIZAS SEÑALIZACION",
      "21. ENGANCHE",
      "22. LLAVE RUEDA",
      "23. CRIQUET",
      "24. MANGUERA DE AIRE",
      "25. MANGUERA DE ENGRASE",
      "26. CAJA HERRAMIENTAS",
      "27. ESCALERAS ACCESO",
      "28. PASARELAS"
    ],
    "LUCES": [
      "29. ALTA/BAJA",
      "30. POSICION",
      "31. GIRO/BALIZA",
      "32. STOP/FRENO",
      "33. MARCHA ATRÁS",
      "34. ANTINIEBLA",
      "35. ILUMINACION DE QUINTA RUEDA",
      "36. INTERIORES CABINA"
    ],
    "SEGURIDAD": [
      "37. CINTURONES DE SEGURIDAD",
      "38. MATAFUEGO (CARGA/VENCIMIENTO)",
      "39. VIGIA DE MOTOR",
      "40. VIGIA DE RUEDAS",
      "41. BANDA REFLECTIVA PARAGOLPE TRASERO",
      "42. ALARMA SONORA DE TOMA DE FUERZA CONECTADA",
      "43. BOTIQUIN DE 1º AUXILIOS",
      "44. EPP"
    ],
    "GENERALES": [
      "45. CINTAS/PASTILLAS FRENOS",
      "46. CHASIS FISURAS INSPECCION VISUAL",
      "47. PAQUETE DE ELASTICO, FUELLE, AMORTIGUADOR",
      "48. LEVAS, PULMONES",
      "49. SISTEMA DE ESCAPES/FUGA",
      "50. EJES DELANTERO Y TRASEROS",
      "51. VERIFICACION GENERAL PLATO DE ENGANCHE",
      "52. DEPOSITO LIQUIDO HIDRAULICO(MOCHILA)",
      "53. CONECTORES HIDRAULICOS",
      "54. CONECTORES MANGUERA DE AIRE",
      "55. ABS"
    ],
    "NEUMATICOS": [
      "56. GOMAS DIRECCION LADO DERECHO",
      "57. GOMAS DIRECCION LADO IZQUIERDO",
      "58. GOMAS TRACCION LADO DERECHO",
      "59. GOMAS TRACCION LADO IZQUIERDO",
      "60. GOMA 3º EJE LADO DERECHO",
      "61. GOMA 3º EJE LADO IZQUIERDO" // ✅ MENTOR: Agregada la rueda faltante
    ]
  };

  // ==========================================
  // CHECK LIST BATEA (50 ÍTEMS TOTAL)
  // ==========================================
  static const Map<String, List<String>> itemsBatea = {
    "EXTERIOR": [
      "1. INTERIOR FIBRA DE VIDRIO",
      "2. TEFLON",
      "3. PLANCHUELAS",
      "4. ESTACA Y ARCOS",
      "5. LONA",
      "6. SOBREBARANDA",
      "7. CHICOTES",
      "8. ROTURAS CHASIS",
      "9. SOLDADURAS",
      "10. CHASIS FISURAS INSPECCION VISUAL"
    ],
    "LUCES": [
      "11. LUCES LATERALES POSICION COLOR AMBAR",
      "12. LUCES FONDO POSICION COLOR ROJAS",
      "13. LUCES STOP/FRENO",
      "14. LUCES GIRO DERECHO/GIRO IZQUIERDO",
      "15. LUCES MARCHA ATRÁS",
      "16. TRES MARIAS ROJAS",
      "17. TRES MARIAS VERDES"
    ],
    "SEGURIDAD": [
      "18. AUXILIO",
      "19. SIMBOLOGIA (80 KM MAX)",
      "20. SIMBOLOGIA TARA CARGA MAXIMA",
      "21. BANDAS REFLECTIVA LATERALES",
      "22. BANDAS REFLECTIVA TRASERAS",
      "23. CONOS DE SEGURIDAD",
      "24. MATAFUEGO (CARGA/VENCIMIENTO)",
      "25. TRABAS DE SEGURIDAD"
    ],
    "GENERALES": [
      "26. CINTAS/PASTILLAS FRENOS",
      "27. LEVAS, PULMONES",
      "28. TACOGRAFO (FUNCIONAMIENTO)",
      "29. CAJA REGISTRO",
      "30. PATINES",
      "31. CAMPANAS",
      "32. MANGUERAS PLASTICOS",
      "33. PULMON FRENO",
      "34. SISTEMA HIDRAULICO (MANGUERAS, CONECTORES)",
      "35. CONTROL DE VALVULA FINAL DE CARRERA",
      "36. CILINDRO LEVANTA BATEA",
      "37. CONTROL DE BALDE DE CARGA",
      "38. SISTEMA DE VIGIA",
      "39. CONECTORES A CUBIERTA",
      "40. CAÑERIA INTERIOR BATEA",
      "41. BAJADA, ROTORES",
      "42. LLANTAS, SUJECIÓN A MASA, TUERCAS",
      "43. MASA CONTROL DE JUEGO",
      "44. PERDIDAS DE GRASA, ZUMBIDO DE BOLLERO"
    ],
    "NEUMATICOS": [
      "45. GOMAS DIRECCION LADO DERECHO",
      "46. GOMAS DIRECCION LADO IZQUIERDO",
      "47. GOMAS TRACCION LADO DERECHO",
      "48. GOMAS TRACCION LADO IZQUIERDO",
      "49. GOMA 3º EJE LADO DERECHO",
      "50. GOMA 3º EJE LADO IZQUIERDO"
    ]
  };
}