// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuKqPyfeujSaendP08jkM5j9bNiOwZmVg',
    appId: '1:444186792745:android:eb89fdab89bf9043f69d38',
    messagingSenderId: '444186792745',
    projectId: 'logisticaapp-e539a',
    storageBucket: 'logisticaapp-e539a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDybNRoE5mutL9IIgRZLhdj47oB0rnDv1s',
    appId: '1:444186792745:ios:949745be7ed5b53cf69d38',
    messagingSenderId: '444186792745',
    projectId: 'logisticaapp-e539a',
    storageBucket: 'logisticaapp-e539a.firebasestorage.app',
    iosBundleId: 'com.example.logisticaAppProfesional',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXoZtGig1_dEg5ImI7iD9x5gzXhvRBASE',
    appId: '1:444186792745:web:8e09b842d82b25ebf69d38',
    messagingSenderId: '444186792745',
    projectId: 'logisticaapp-e539a',
    authDomain: 'logisticaapp-e539a.firebaseapp.com',
    storageBucket: 'logisticaapp-e539a.firebasestorage.app',
    measurementId: 'G-3T2ZQS8NST',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXoZtGig1_dEg5ImI7iD9x5gzXhvRBASE',
    appId: '1:444186792745:web:0891d0a876c5ded5f69d38',
    messagingSenderId: '444186792745',
    projectId: 'logisticaapp-e539a',
    authDomain: 'logisticaapp-e539a.firebaseapp.com',
    storageBucket: 'logisticaapp-e539a.firebasestorage.app',
    measurementId: 'G-V4B4HZYMSE',
  );

}