// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Ll6WhwlIHd_Mr08jfMH9Yda1IhWzdfs',
    appId: '1:808925655961:android:9238749f27b21130a4d908',
    messagingSenderId: '808925655961',
    projectId: 'coopertrans-movil',
    storageBucket: 'coopertrans-movil.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI1z5ZtDvuK5KpI2g483rnHVKb9zUg29M',
    appId: '1:808925655961:ios:35db79f4532b71caa4d908',
    messagingSenderId: '808925655961',
    projectId: 'coopertrans-movil',
    storageBucket: 'coopertrans-movil.firebasestorage.app',
    iosBundleId: 'com.coopertrans.movil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbtUdJmSyxQobtFpsIds6mutKCbEy0iuw',
    appId: '1:808925655961:web:1ca61bae2dc19f23a4d908',
    messagingSenderId: '808925655961',
    projectId: 'coopertrans-movil',
    authDomain: 'coopertrans-movil.firebaseapp.com',
    storageBucket: 'coopertrans-movil.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbtUdJmSyxQobtFpsIds6mutKCbEy0iuw',
    appId: '1:808925655961:web:f5f1aa100c059ddba4d908',
    messagingSenderId: '808925655961',
    projectId: 'coopertrans-movil',
    authDomain: 'coopertrans-movil.firebaseapp.com',
    storageBucket: 'coopertrans-movil.firebasestorage.app',
  );

}